default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: sodas_development

test:
  <<: *default
  database: sodas_test

production:
  <<: *default
  database: sodas_production
  username: postgres
  password: postgres